### ISSUE TITLE
Yes/No Question game (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#251]
## Still to be done
- [x] Images of the products should be aligned, possibly in a grid, possibly minimized ?
  - [ ] <img width="426" alt="image" src="https://user-images.githubusercontent.com/1689815/177146401-789f7b57-2eda-4872-8d58-866086d3f0a4.png">
- [x] Buttons should be centered and separated by a few horizontal pixels in mobile mode
  - [ ] 
- [ ] View should be centered in mobile mode
  - [ ] #101
  - [ ] No question remaining
    - [ ] #102
- [x] #386
- [x] Remaining >> Remaining questions
- [ ] Allow to type a value by adding a field (ideally with autocompletion)
- [x] Honor English shorcuts for English
- [ ] ![Image](https://user-images.githubusercontent.com/1689815/177634806-68bae3bc-d052-4509-bac9-c7149b5a7a53.png)
- [ ] Add a view with only products which don't have a category at all (states=categories-to-be-completed) for the category game

---

## Done - Category/Brand game
- [x] The Hunger Games logo is not aligned with the menus in the top bar
  - [ ] <img width="706" alt="image" src="https://user-images.githubusercontent.com/1689815/177146513-265ea486-6240-4f3a-9e50-86e51b2d7ba5.png">
- [x] Add padding after "See examples of this brand"
  - [ ] <img width="347" alt="image" src="https://user-images.githubusercontent.com/1689815/177146573-788cd6f0-607a-4694-8b5c-22da329c8380.png">
- [x] View and Edit button should be augmented with icons, and possibly be turned into buttons
  - [ ] <img width="347" alt="image" src="https://user-images.githubusercontent.com/1689815/177146705-29b2bb57-8f79-4c45-970f-ec03176fa9e7.png">
- [x] brand / category / label dropdown should be more explicit "Only show brands" "Only show categories"
    - [x] Offer to remove value when no question left for this value <img width="693" alt="image" src="https://user-images.githubusercontent.com/1689815/177630690-cb21aafd-6767-405d-b758-fff33e03d6fd.png">

### Part of
- #37

**Comment by teolemon** [comment]
yep, can you comment on this issue, so that I can assign it to you ?
https://github.com/openfoodfacts/hunger-games/issues/386

**Comment by Apurv428** [comment]
@teolemon can you give more details about the issue: Images of the products should be aligned, possibly in a grid, possibly minimized?
I'm interested in working on it.

**Comment by djv03** [comment]
> 

can I work on this? Is this still open to work on?

**Comment by alexfauquette** [comment]
@djv03 What would you like to do on this one?

If you want there is #420 which might be feasible
