### ISSUE TITLE
Navigation (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#252]
### What
- [x] Use the full width of the page
  - [x] <img width="1298" alt="image" src="https://user-images.githubusercontent.com/1689815/177147873-e0a1c38b-2ec5-46e0-a584-41f6b82bd817.png">
- [x] Put settings as an icon on the right
- [x] Change the color according to the new graphic charter of the app (beige)

### Part of
- #37
