### ISSUE TITLE
[Epic] Nutrition Game

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#70]
Epic: Nutrition Game

### Description
Make an easy-to-use interface for filling nutrition data table

### What would a demo look like

The first idea is something very simple: one side of the screen for the picture, the second for the table to fill

Some edge case we will face: the table needs to include a quantification (is the value equal, an upper or a lower bound) and the unit

![image](https://user-images.githubusercontent.com/45398769/181105685-71f8d8a8-adc6-4aae-a9b0-43de33faf7ec.png)

### Tasks
- [ ] Add a page for nutrition game
- [ ] Create a controllable table
- [ ] Send annotations to OFF server
- [ ] Use Robotof to refill some inputs
